# Shell variables
# Generated by 'wal'
wallpaper='/home/youkwhd/_wp/wallpaper-6.jpg'

# Special
background='#000001'
foreground='#a6cddf'
cursor='#a6cddf'

# Colors
color0='#000001'
color1='#95474C'
color2='#186593'
color3='#557290'
color4='#2B8CAB'
color5='#5C95A9'
color6='#4FAFD1'
color7='#a6cddf'
color8='#748f9c'
color9='#95474C'
color10='#186593'
color11='#557290'
color12='#2B8CAB'
color13='#5C95A9'
color14='#4FAFD1'
color15='#a6cddf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
