--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/youkwhd/_wp/wallpaper-6.jpg"

-- Special
background="#000001"
foreground="#a6cddf"
cursor="#a6cddf"

-- Colors
color0="#000001"
color1="#95474C"
color2="#186593"
color3="#557290"
color4="#2B8CAB"
color5="#5C95A9"
color6="#4FAFD1"
color7="#a6cddf"
color8="#748f9c"
color9="#95474C"
color10="#186593"
color11="#557290"
color12="#2B8CAB"
color13="#5C95A9"
color14="#4FAFD1"
color15="#a6cddf"
